version: "3.8"

services:
  gateway:
    build:
      context: ../services/gateway-service
      dockerfile: Dockerfile.dev
    volumes:
      - ../services/gateway-service:/app
    ports:
      - "8080:8080"
    environment:
      - WEIGHT_SERVICE_GRPC_ADDR=weight:50052
      - USER_SERVICE_GRPC_ADDR=user:50051
      - MEAL_SERVICE_GRPC_ADDR=meal:50053
      - ENVIRONMENT=dev
    depends_on:
      - weight

  weight:
    build:
      context: ../services/weight-service
      dockerfile: Dockerfile.dev
    volumes:
      - ../services/weight-service:/app
    ports:
      - "50052:50052" # Changed to match the gRPC port
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:password@postgres:5432/weight_service?sslmode=disable
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      nats:
        condition: service_started

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: weight_service,exercise_service,workout_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts/create-multiple-dbs.sh:/docker-entrypoint-initdb.d/create-multiple-dbs.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nats:
    image: nats:2
    ports:
      - "4222:4222"

volumes:
  postgres_data:
